base.captcha.props.kaptcha:
  #是否有边框 可选yes 或者 no
  border: 'no'
  #边框颜色
#  border.color: '105,179,90'
  textproducer:
    char:
      #验证码文本字符长度 默认为5
      length: '4'
      #验证码文本字符内容范围  默认为abcde2345678gfynmnpwx
      string: '0123456789'
    font:
      #验证码文本字符颜色
      color: '193,3,3'
      #验证码文本字体样式
      names: '微软雅黑,宋体,楷体'
      #验证码文本字符大小
      size: '40'
  image:
    #验证码图片的宽度 默认200
    width: '160'
    #验证码图片的高度 默认50
    height: '60'



