#mybatis:
##  config-location: classpath:mybatis-config.xml
#  mapper-locations: classpath*:mapper/**/**Mapper.xml
#  type-aliases-package: classpath*:com.xxx.yyy.**.domain
#  configuration:
#    call-setters-on-nulls: true

pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: false
  support-methods-arguments: true

mybatis-plus:
  mapper-locations: /mapper/**/**Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.xxx.yyy.**.domain.**
  global-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: 3
      #字段策略 0:"忽略判断",1:"非 NULL 判断",2:"非空判断"
      field-strategy: 2
      #驼峰下划线转换
      db-column-underline: true
      #刷新mapper 调试神器
      refresh-mapper: true
      #数据库大写下划线转换
      #capital-mode: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false