spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    properties:
      hibernate.show_sql: false
      hibernate.format_sql: false
      #从domain生成表到数据库
      #hibernate.hbm2ddl.auto: create