base.user.names:
  "Alex,
  Alexis,
  Andy,
  Angel,
  Ash,
  Ashley,
  Benny,
  Bernie,
  Bertie,
  Beverly,
  Billie,
  Blair,
  Bobbie,
  Brett,
  Carol,
  Casey,
  Charlie,
  Cis,
  Chris,
  Christian,
  Clare,
  Clem,
  Connie,
  Cory,
  Courtney,
  Dale,
  Danny,
  Darcy,
  Daryl,
  Denny,
  Dorian,
  Eddy,
  Em,
  Ernie,
  Fran,
  Franky,
  Freddy,
  Gabby,
  Gayle,
  Gene,
  Glynn,
  Hilary,
  Izzy,
  Jackie,
  Jamie,
  Jem,
  Jerry,
  Jess,
  Jo,
  Jody,
  Jordan,
  Jude,
  Kelly,
  Kim,
  Kit,
  Kris,
  Lee,
  Lesley,
  Lindsey,
  Lonnie,
  Lou,
  Lynn,
  Marion,
  Marty,
  Matty,
  Max,
  Mel,
  Mickey,
  Morgan,
  Natty,
  Nicky,
  Noel,
  Normie,
  Norrie,
  Ollie,
  Pat,
  Payton,
  Phil,
  Randy,
  Ray,
  Reggie,
  Ricky,
  Robby,
  Robin,
  Ronny,
  Ruby,
  Sam,
  Sandy,
  Shannon,
  Shelley,
  Shelly,
  Sidney,
  Stacy,
  Steph,
  Taylor,
  Terry,
  Theo,
  Tony,
  Tracy,
  Val,
  Vic,
  Vinnie,
  Willie,
  Winnie,
  "