eureka:
  instance:
    #（开发和测试环境）
    #服务刷新时间配置，每隔这个时间会主动心跳一次, 默认30s
    lease-renewal-interval-in-seconds: 6
    #（开发和测试环境）
    #服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
    #注意，EurekaServer一定要设置eureka.server.eviction-interval-timer-in-ms否则这个配置无效，
    #这个配置一般为服务刷新时间配置的三倍, 默认90s
    lease-expiration-duration-in-seconds: 15

spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.DriverSpy
#    username: sa
#    password: 123456
#    url: jdbc:log4jdbc:mysql://localhost:3306/sa?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: He800@123
    url: jdbc:log4jdbc:mysql://192.168.60.5:3306/demo_dev?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
  redis:
    database: 1
    host: 192.168.60.5
    password: He800@123
    lettuce:
      pool:
        max-active: 200
        max-idle: 50
        max-wait: 5s
        min-idle: 0
    port: 6379
    timeout: 1m

# 测试环境用于接受发送的邮件地址，以免乱发出去
base.pm.mail.sendMailConfig:
  testReceptionAddress: 728607521@qq.com
  send : 1 #0 不发送邮件，1 发送邮件

# 客户经理和服务人员每天查询次数限制
base.userSearch.limit.countOfDay: 100

# 用户一个小时内密码错误限制次数
base.userPwdError.limit.countOfHour: 3

base.sms.limit.countOfDay: 100

# 服务人员服务订单的上限
base.servicer.service.limit: 500

base.pm.promotion:
  return:
    # 活动线下返现开关
    offline: false
    # 需要加入返现记录的奖品项编号
    reward:
      - ORDER_COUPONS

  extraCondition:
    SHARE_ORDER:
      payAmount_min: 3000

# 推广活动-公司名字评分
base.pm.spread.company:
  names:
    - "麦积/麦积财税/麦积财税集团"
  scores:
    - 99

