eureka:
  server:
    #自我保护模式，当出现出现网络分区、eureka在短时间内丢失过多客户端时，会进入自我保护模式，
    #时即一个服务长时间没有发送心跳，eureka也不会将其删除，默认为true
    enable-self-preservation: false

base:
  #elastic-search 配置文件名，不要后缀.yml
  es-file-name: 'base-es-prod'
#  config-search-path: config-server/src/main/resources/config
  config-search-native-path: /data/he800/server/config

#config server 默认使用 git，除非profiles中使用native或者subversion
spring:
  cloud:
    config:
      server:
        prefix: config
        default-label: '@git.branches@'
        git:
          uri: git://192.168.60.5/base-components.git
          search-paths: ${base.config-search-path}/**
          username: ligeng
          password: ligeng